# Required
sonar.projectKey=SOLIDFramework
sonar.projectName=SOLIDFramework
sonar.projectVersion=1.0

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Test coverage (optional if using Jacoco)
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.token=sqa_988ad24dd9ca8cf562d733aec4e255f8477ffe7b


#sqa_988ad24dd9ca8cf562d733aec4e255f8477ffe7b